### ISSUE TITLE
Develop Mac versions of solutions for a few labs

### ISSUE THREAD

**Issue by dendibakh** [dendibakh/perf-ninja#60] opened 2022-09-30 00:02 UTC
Currently the following labs don't have solutions for Mac M1 platform:

```
  ["memory_bound"]["huge_pages_1"]          - need to check huge pages on Mac
  ["misc"]["io_opt1"]                       - mmap on Mac
  ["core_bound"]["compiler_intrinsics_1"]   - NEON version
  ["core_bound"]["compiler_intrinsics_2"]   - NEON version
```
This prevents automated benchmarking of their speedups in CI.

**Comment by andrewevstyukhin** [comment] 2022-09-30 06:44
You can try to use "sse2neon"

**Comment by Cosmin-B** [comment] 2022-12-11 21:50
Hi @dendibakh, I can confirm that using sse2neon to solve the  ["core_bound"]["compiler_intrinsics_1"]  does work, albeit it is a bit slower than writing pure ARM Neon code, due to the differences in the architectures and the more instructions need to translate from SSE to NEON using the same x86 algorithms.

You can check the[ CI Job](https://github.com/dendibakh/perf-ninja/actions/runs/3670946363/jobs/6205815073) as well as my [branch with commits ](https://github.com/dendibakh/perf-ninja/commits/private/cosmin).

Once again, thank you for the excellent work!

**Comment by Cosmin-B** [comment] 2022-12-11 21:51
Ups, i did not mean to close this

**Comment by dendibakh** [comment] 2022-12-13 15:04
> Hi @dendibakh, I can confirm that using sse2neon to solve the ["core_bound"]["compiler_intrinsics_1"] does work, 

This is nice to know! I haven't used sse2neon before.

> albeit it is a bit slower than writing pure ARM Neon code, due to the differences in the architectures and the more instructions need to translate from SSE to NEON using the same x86 algorithms.

I can't find your NEON implementation. Can you please share it?

> Once again, thank you for the excellent work!

You're welcome! :)

**Closed** 2022-12-13 15:41 UTC

**Comment by Cosmin-B** [comment] 2022-12-13 15:45
Hey @dendibakh 

This is it! [implementation](https://github.com/dendibakh/perf-ninja/blob/private/cosmin/labs/core_bound/compiler_intrinsics_1/solution.cpp). You can look at the history as well as see that I added the sse2neon.h in the compiler_intrinsics_1 folder. You can add that as a dependency that you would pull automatically on ARM devices compatible with Neon.

P.S.: I am sorry for closing the issue again. The GitHub interface is not friendly enough for me.

Kind regards,
Cosmin

**Comment by dendibakh** [comment] 2022-12-13 15:59
I thought you said you wrote NEON instrinsics yourself without using sse2neon library, no?

**Comment by Cosmin-B** [comment] 2022-12-14 18:58
>I can confirm that using sse2neon to solve the ["core_bound"]["compiler_intrinsics_1"] does work, albeit it is a bit slower than writing pure ARM Neon code

Hey, @dendibakh, I am sorry for the misunderstanding. However, I did not say that. I only said that I confirmed that it could be done using the sse2neon library.

Kind regards,
Cosmin

**Comment by dendibakh** [comment] 2022-12-15 14:44
> > I can confirm that using sse2neon to solve the ["core_bound"]["compiler_intrinsics_1"] does work, albeit it is a bit slower than writing pure ARM Neon code
> 
> Hey, @dendibakh, I am sorry for the misunderstanding. However, I did not say that. I only said that I confirmed that it could be done using the sse2neon library.
> 
> Kind regards, Cosmin

Ok, got it, no worries. Thanks for sharing your experiments.
